options:
  auth-basic-password:
    type: string
    default: ""
    description: |
      Password for basic (htpasswd) authentication. Set this to something
      other than an empty string to configure basic auth for the registry.
  auth-basic-user:
    type: string
    default: "admin"
    description: Username for basic (htpasswd) authentication.
  auth-token-issuer:
    type: string
    default: ""
    description: The name on the certificate that authentication tokens must me signed by.
  auth-token-realm:
    type: string
    default: ""
    description: The location from which clients should fetch authentication tokens.
  auth-token-root-certs:
    type: string
    default: ""
    description: The root certificate bundle (base64 encoded) for the authentication tokens.
  auth-token-service:
    type: string
    default: ""
    description: The name of the server which authentication tokens will be addressed to.
  http-host:
    type: string
    default: ""
    description: |
      The external URL where the docker registry is hosted. This URL will
      be prepended to all locations generated by the docker registry to
      ensure that those URLs are reachable by the client.  For example
      "https://example.com/docker-registry/". Any path component must
      include a trailing "/". If this is not configured then the docker
      registry will derive its location from the incoming requests.
  log-level:
    type: string
    default: "info"
    description: Logging output level ('error', 'warn', 'info', or 'debug').
  registry-image:
    type: string
    default: "registry:2"
    description: Registry image.
  registry-name:
    type: string
    default: "registry"
    description: Name of the registry container.
  registry-port:
    type: int
    default: 5000
    description: The external port on which the docker registry listens.
  storage-read-only:
    type: boolean
    default: false
    description: Controls the storage maintenance option "readonly".
  storage-swift-authurl:
    type: string
    default: ""
    description: The URL of the keystone used to authenticate to swift.
  storage-swift-container:
    type: string
    default: ""
    default: docker-registry
    description: The name of the swift container that will hold the images.
  storage-swift-password:
    type: string
    default: ""
    description: The password to use to access swift.
  storage-swift-region:
    type: string
    default: ""
    description: The region containing the swift service.
  storage-swift-tenant:
    type: string
    default: ""
    description: The tenant containing the swift service.
  storage-swift-username:
    type: string
    default: ""
    description: The username to use to access swift.
  tls-ca-blob:
    type: string
    default: ""
    description: Base64 encoded TLS CA certificate (overwrites tls-cert-path file).
  tls-cert-blob:
    type: string
    default: ""
    description: Base64 encoded TLS certificate (overwrites tls-cert-path file).
  tls-key-blob:
    type: string
    default: ""
    description: Base64 encoded TLS certificate private key (overwrites tls-key-path file).
  tls-ca-path:
    type: string
    default: "/etc/docker/registry/ca.crt"
    description: Path to the TLS CA certificate.
  tls-cert-path:
    type: string
    default: "/etc/docker/registry/registry.crt"
    description: Path to the TLS certificate.
  tls-key-path:
    type: string
    default: "/etc/docker/registry/registry.key"
    description: Path the the TLS certificate private key.
